config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/my_bookmarks'
  get 'topics/my_topics'

  resources :topics do
    resources :bookmarks, except: [:index, :show, :edit, :update]
  end

  resources :bookmarks, only: [:index] do
    resources :likes, only: [:create, :destroy]
  end

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/FAQ'
  get 'welcome/search'
  post :incoming, to: 'incoming#create'
  root to: 'welcome#index'
  devise_for :users
  resources :users
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer          not null, primary key
#  title      :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#

class Topic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :history

  validates_length_of :title, minimum: 1
  belongs_to :user
  has_many :bookmarks
  has_many :likes, dependent: :destroy

  def self.search(search)
    where('title like ?', "%#{search}%")
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    authorize @topics
  end

  def show
    @topic = Topic.friendly.find(params[:id])
    authorize @topic
    @bookmarks = @topic.bookmarks.includes(:user).includes(:likes)
  end

  def new
    @topic = Topic.new
    @topic.user = current_user
    authorize @topic
  end

  def edit
    @topic = Topic.friendly.find(params[:id])
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    @topic.user = current_user
    if @topic.save
      flash[:notice] = 'Topic was saved successfully.'
      redirect_to topics_path
    else
      flash[:error] = 'Error saving topic, please try again.'
      render :new
    end
  end

  def update
    @topic = Topic.friendly.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)
      flash[:notice] = 'Topic was updated successfully.'
      redirect_to topics_path
    else
      flash[:error] = 'Topic was not updated. Please try again.'
      redirect_to topics_path
    end
  end

  def destroy
    @topic = Topic.friendly.find(params[:id])
    title = @topic.title
    authorize @topic
    if @topic.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully"
      redirect_to topics_path
    else
      flash[:error] = 'There was an error deleting the topic. Please try again'
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
%h5 New Topic
= form_for @topic do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control field-small', placeholder: "Enter topic"
  .form-group
    = f.submit "Save", class: 'btn btn-success btn-sm'

app/views/topics/edit.html.haml
.container
  %h1 Edit Topic
  = form_for @topic do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.submit "Save", class: 'btn btn-success'

app/views/topics/index.html.haml
.container
  .row
    %h1 All Topics
    %small You may edit or delete topics you have created
    - @topics.each do |topic|
      %h3
        - if policy(topic).destroy?
          = link_to topic, data: { confirm: 'Are you sure you want to delete this topic?' }, method: :delete, class: 'btn btn-danger btn-xs' do
            %span.has-tooltip{"data-toggle" => "tooltip", :title => "Delete Topic"}
              %span.glyphicon.glyphicon-trash
          = link_to edit_topic_path(topic), class: 'btn btn-success btn-xs' do
            %span.has-tooltip{"data-toggle" => "tooltip", :title => "Edit Topic"}
              %span.glyphicon.glyphicon-pencil
          = link_to "#{topic.title}", topic
        - else
          %h3= link_to "#{topic.title}", topic
    - if current_user
      = link_to "My Topics", topics_my_topics_path, class: 'btn btn-info'
      = link_to "New Topic", new_topic_path, class: 'btn btn-success'
    %br/

app/views/topics/my_topics.html.haml
.container
  .row
    %h1 My Topics
    - current_user.topics.each do |topic|
      %h3
        = link_to topic, data: { confirm: 'Are you sure you want to delete this topic?' }, method: :delete, class: 'btn btn-danger btn-xs' do
          %span.has-tooltip{"data-toggle" => "tooltip", :title => "Delete Topic"}
            %span.glyphicon.glyphicon-trash
        = link_to edit_topic_path(topic), class: 'btn btn-success btn-xs' do
          %span.has-tooltip{"data-toggle" => "tooltip", :title => "Edit Topic"}
            %span.glyphicon.glyphicon-pencil
        = link_to " #{topic.title}", topic
    = link_to "All Topics", topics_path, class: 'btn btn-info'
    = link_to "New Topic", new_topic_path, class: 'btn btn-success'

app/views/topics/new.html.haml
.container
  .row
    %h1 New Topic
    = form_for @topic do |f|
      .form-group
        = f.label :title
        %br/
        = f.text_field :title, class: 'form-control', placeholder: "Enter topic"
      .form-group
        = f.submit "Save", class: 'btn btn-success btn-sm'

app/views/topics/show.html.haml
.container
  .row
    - if @topic
      %h3
        = link_to @topic, data: { confirm: 'Are you sure you want to delete this topic?' }, method: :delete, class: 'btn btn-danger btn-xs' do
          %span.has-tooltip{"data-toggle" => "tooltip", :title => "Delete Topic"}
            %span.glyphicon.glyphicon-trash
        = link_to edit_topic_path(@topic), class: 'btn btn-success btn-xs' do
          %span.has-tooltip{"data-toggle" => "tooltip", :title => "Edit Topic"}
            %span.glyphicon.glyphicon-pencil
        Topic: #{@topic.title}
      %h4= "Bookmarks:" if @bookmarks.present?
      %ul
        = render partial: 'bookmarks/bookmark', collection: @bookmarks, locals: { topic_id: @topic.id }
      = render partial: 'bookmarks/form', locals: { topic_id: @topic.id }
    - else
      = link_to "New Topic", new_topic_path, class: 'btn btn-warning'
    %br/