config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/my_bookmarks'
  get 'topics/my_topics'

  resources :topics do
    resources :bookmarks, except: [:index, :show, :edit, :update]
  end

  resources :bookmarks, only: [:index] do
    resources :likes, only: [:create, :destroy]
  end

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/FAQ'
  get 'welcome/search'
  post :incoming, to: 'incoming#create'
  root to: 'welcome#index'
  devise_for :users
  resources :users
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id          :integer          not null, primary key
#  bookmark_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :load_bookmark_and_like

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.build(bookmark: @bookmark)
    authorize @like

    if @like.save
      flash[:notice] = 'Bookmark liked.'
      redirect_to request.referer
    else
      flash[:error] = 'Please try again later.'
      redirect_to request.referer
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = Like.find(params[:id])
    authorize @like

    if @like.destroy
      flash[:notice] = 'Like deleted.'
      redirect_to request.referer
    else
      flash[:error] = 'Please try again later.'
      redirect_to :back
    end
  end

  private

  def load_bookmark_and_like
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = @bookmark.likes.where(user_id: current_user.id).first
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
- if policy(Like.new).create?
  - like = current_user.like_for(bookmark)
  - if like.present?
    %span.label.label-primary Liked
    = link_to bookmark_like_path(bookmark, like), class: 'btn btn-inverse btn-xs', method: :delete do
      %span.has-tooltip{"data-toggle" => "tooltip", :title => "Unlike Bookmark"}
        %i.glyphicon.glyphicon-thumbs-down   - else
    = link_to bookmark_likes_path(bookmark), class: 'btn btn-inverse btn-xs', method: :post do
      %span.has-tooltip{"data-toggle" => "tooltip", :title => "Like Bookmark"}
        %i.glyphicon.glyphicon-thumbs-up <br \>