config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/my_bookmarks'
  get 'topics/my_topics'

  resources :topics do
    resources :bookmarks, except: [:index, :show, :edit, :update]
  end

  resources :bookmarks, only: [:index] do
    resources :likes, only: [:create, :destroy]
  end

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/FAQ'
  get 'welcome/search'
  post :incoming, to: 'incoming#create'
  root to: 'welcome#index'
  devise_for :users
  resources :users
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default("")
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  role                   :integer
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_id          :integer
#  invited_by_type        :string
#  invitations_count      :integer          default(0)
#  public                 :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, if: :new_record?

  has_many :topics
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_bookmarks, through: :likes, source: :bookmark

  def pending_invite?
    invitation_created_at && !invitation_accepted_at
  end

  def set_default_role
    self.role ||= :user
  end

  def like_for(bookmark)
    likes.find_by(bookmark_id: bookmark.id)
  end

  scope :visible_to, -> (user) { user ? all : where(public: true) }

  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  # POST /users
  # POST /users.json

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver_now

        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json do
          render json: @user, status: :created,
                 location: @user
        end
      else
        format.html { render action: 'new' }
        format.json do
          render json: @user.errors, status:
                      :unprocessable_entity
        end
      end
    end
  end

  def show
    @user = User.find(params[:id])
    authorize @user
    @user_bookmarks = @user.bookmarks
    @like_bookmarks = Like.where(user_id: current_user.id)
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, notice: 'User updated.'
    else
      redirect_to users_path, alert: 'Unable to update user.'
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end
end

app/views/users/_user.html.haml
%td
  = link_to user.email, user
%td
  = form_for(user) do |f|
    = f.select(:role, User.roles.keys.map {|role| [role.titleize,role]})
    = f.submit 'Change Role', :class => 'button-xs'
%td
  = link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user

app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %tbody
          - @users.each do |user|
            %tr
              = render user

app/views/users/show.html.haml
.container
  .row
    %h1= "#{current_user.name}"
    .col-md-4
      %h2 My Topics
      - current_user.topics.each do |topic|
        %h3
          = link_to "#{topic.title}", topic
          %br/
        - topic.bookmarks.each do |bookmark|
          %h5
            = link_to "#{bookmark.url}", bookmark.url
            %br/
      = link_to "All Topics", topics_path, class: 'btn btn-info btn-top btn-bottom'
    .col-md-4
      %h2 My Bookmarks
      - current_user.bookmarks.each do |bookmark|
        %h4
          = link_to "#{bookmark.url}", bookmark.url
          %small= link_to " (#{bookmark.topic.title})", bookmark.topic
          %br/
      = link_to "All Bookmarks", bookmarks_path, class: 'btn btn-info btn-top btn-bottom'
    .col-md-4
      %h2 Liked Bookmarks
      - current_user.liked_bookmarks.each do |bookmark|
        %h5
          = link_to "#{bookmark.url}", bookmark.url
          = render partial: 'likes/like', locals: { bookmark: bookmark }