config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/my_bookmarks'
  get 'topics/my_topics'

  resources :topics do
    resources :bookmarks, except: [:index, :show, :edit, :update]
  end

  resources :bookmarks, only: [:index] do
    resources :likes, only: [:create, :destroy]
  end

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/FAQ'
  get 'welcome/search'
  post :incoming, to: 'incoming#create'
  root to: 'welcome#index'
  devise_for :users
  resources :users
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def FAQ
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/FAQ.html.haml
.container
  .row
    %h1 Frequently Asked Questions
    %ol
      %h3
      %li I cannot login
      %p
        I did not receive a confirmation email.
        \#{link_to "Resend Email", new_user_confirmation_path}
      %p
        I forgot my password
        \#{link_to "Reset Password", new_user_password_path}
      %h3
      %li I want to change my user information
      %p= link_to "User Profile", edit_user_registration_path

app/views/welcome/about.html.haml
.container
  %h1 About Mark1
  .jumbotron
    .row
      %h2
        Created by: Andrew Scott

app/views/welcome/index.html.haml
.container
  - unless current_user
    .jumbotron.no-margin
      .row.no-margin.no-padding
        =image_tag  "http://i.imgur.com/0QHoXMH.png", :class => "my_class"
        %p Are you looking for a new way to organize your bookmarks and share them with friends?
      .row.no-margin
        .col-md-6.pull-left.no-padding
          %h2= link_to "Create a new account", new_user_registration_path
          %br/
        .col-md-6.no-padding
          %h2 Already have an account?
          %h4= link_to "Sign in", new_user_session_path
  - else
    .jumbotron.no-margin
      .row.no-margin.no-padding
        =image_tag  "http://i.imgur.com/0QHoXMH.png", :class => "my_class"
        %p Are you looking for a new way to organize your bookmarks and share them with friends?
    .row.no-margin
      .col-md-4.pull-left
        %br/
        .panel.panel-primary
          .panel-heading
          .panel-body
            %h3= link_to "All Topics", topics_path
            %h3= link_to "My Topics", topics_my_topics_path
      .col-md-4
        %br/
        .panel.panel-primary
          .panel-heading
          .panel-body
            %h3
              = link_to "All Bookmarks", bookmarks_path
              %h3= link_to "My Bookmarks", bookmarks_my_bookmarks_path
      .col-md-4
        %br/
        .panel.panel-primary
          .panel-heading
          .panel-body
            %h3= link_to "Invite Friends", new_invitation_path(:user)
            %h3 &nbsp;